-- MySQL Script generated by MySQL Workbench
-- Tue Mar 22 15:17:06 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_onde_tem_role
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_onde_tem_role
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_onde_tem_role` DEFAULT CHARACTER SET utf8 ;
USE `db_onde_tem_role` ;

-- -----------------------------------------------------
-- Table `db_onde_tem_role`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_onde_tem_role`.`tb_tema` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cultural` VARCHAR(255) NOT NULL,
  `religioso` VARCHAR(255) NOT NULL,
  `consumo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_onde_tem_role`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_onde_tem_role`.`tb_usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `guia` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_onde_tem_role`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_onde_tem_role`.`tb_postagem` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `local` VARCHAR(255) NOT NULL,
  `dataHora` DATETIME NOT NULL,
  `contato` INT NOT NULL,
  `valor` INT NOT NULL,
  `turismo` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  `tema_id` BIGINT NULL,
  `usuario_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_postagem_tb_tema_idx` (`tema_id` ASC) VISIBLE,
  INDEX `fk_tb_postagem_tb_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_postagem_tb_tema`
    FOREIGN KEY (`tema_id`)
    REFERENCES `db_onde_tem_role`.`tb_tema` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_postagem_tb_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_onde_tem_role`.`tb_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
